<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-sm form-control ng-isolate-scope</name>
   <tag></tag>
   <elementGuidId>d9bb4c94-73f5-4d3e-b179-472797f7e6fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.input-sm.form-control.ng-isolate-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2c2c80c-8629-49e9-af96-c611330fc501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>st-search</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>f23a73e0-4804-49a5-96d0-8e9a747e3067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>search for firstname</value>
      <webElementGuid>2b7a5719-a1e2-406c-a00d-e219ce3cf7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sm form-control ng-isolate-scope</value>
      <webElementGuid>76438d78-aa4a-4bb3-96da-f8ff2977ea70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>8689bba9-a511-47ca-9095-d4d4d3984a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;table table-striped ng-isolate-scope&quot;]/thead[1]/tr[2]/th[1]/input[@class=&quot;input-sm form-control ng-isolate-scope&quot;]</value>
      <webElementGuid>93da2375-bc92-4347-908c-a9d1dd909e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='search']</value>
      <webElementGuid>d3397052-99f7-41be-8e87-955bffb3def1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e9f8df00-d113-4e16-b34e-fd95facdc980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'search for firstname' and @type = 'search']</value>
      <webElementGuid>454f6c14-fc1d-404e-97e6-083e226bea57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
