<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-sm form-control ng-isolate-scope_1</name>
   <tag></tag>
   <elementGuidId>7b988f20-cfb9-4399-bdc0-b34b2ebcab77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th:nth-of-type(2) > input.input-sm.form-control.ng-isolate-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35e7f4ea-3d2a-4851-b937-79ecb3208330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>global search</value>
      <webElementGuid>01ee406d-0e62-4bc1-ad6d-8a78b5c8fe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sm form-control ng-isolate-scope</value>
      <webElementGuid>ff37dc91-888d-448f-8b72-d7237d19680c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>18b1dddd-5c74-4aad-8ef6-106ddfcdb067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;table-container&quot;]/table[@class=&quot;table table-striped ng-isolate-scope&quot;]/thead[1]/tr[2]/th[2]/input[@class=&quot;input-sm form-control ng-isolate-scope&quot;]</value>
      <webElementGuid>dc50f609-6fb1-4a2d-886c-4f01c01b20be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='search'])[2]</value>
      <webElementGuid>aee57ecb-a80f-430a-8535-70a728fd39df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/input</value>
      <webElementGuid>ce76c270-161c-4f8f-b698-2a7ea202f780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'global search' and @type = 'search']</value>
      <webElementGuid>6bb9f243-795e-4000-afd5-29b2a3a2eaaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
