<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_search-field</name>
   <tag></tag>
   <elementGuidId>e89a71a1-cd71-4d2d-8d51-e39022b77aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7db0dce9-b574-4136-bf13-4ff6e08527b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-field</value>
      <webElementGuid>ec0c762f-343c-4d50-9e5d-99080264edc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>46df2eb2-f686-484c-ba31-52a6f44b4671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>d1745df7-22c7-415d-9231-b8bc5fbca728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-field&quot;)</value>
      <webElementGuid>ff043b32-0404-41b2-8d14-9ab7108186bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-field']</value>
      <webElementGuid>1c2225c8-bb5e-4aa8-ade1-b00e90c21841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>bd4d72d5-ee15-412c-a82c-0a931faae46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>60699351-5451-4794-80df-541c835072f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-field' and @type = 'search']</value>
      <webElementGuid>e5039237-1494-4b66-a5d9-89d9e36f64f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
