<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>fd3db0d1-eb8a-4f20-9f85-ef39ae66988e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92da3608-a83c-46a1-bd86-053e5e9e8b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3854bc7f-0497-41b0-951c-2892ce3740cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uid</value>
      <webElementGuid>cfc2f709-92da-4dbd-8ca1-cbd47a6b8fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uid</value>
      <webElementGuid>b8b6696e-197a-4421-a153-dc4e1b51294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uid&quot;)</value>
      <webElementGuid>8c9a7769-d263-449c-bd86-dd33538113d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uid']</value>
      <webElementGuid>fab3b5a2-00cd-4f8c-a108-8b673afacde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>55aaddf1-4a98-4572-a0a5-a37c692f0456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>c837a579-6033-4e38-8f35-7286c6b6a8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uid' and @name = 'uid']</value>
      <webElementGuid>16063a56-6d2e-4fb3-89b6-1e383d2cd225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
