<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>b6b51012-0583-4afa-a5e7-509ff26d9aea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87cc7a17-f6c2-4681-8122-1b0985998ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2f89cb55-075b-4a2d-b76f-1049241bd5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passw</value>
      <webElementGuid>103300ee-530b-4c7d-8178-08faf7a14e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passw</value>
      <webElementGuid>0bbdccb7-07bf-4836-9ae2-ff71220754a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passw&quot;)</value>
      <webElementGuid>4da908ac-8cb4-42d3-b856-02a2295529b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passw']</value>
      <webElementGuid>36a3835f-5977-4ecf-8362-5884c6072fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>4b1e67e3-0bc6-4070-85ff-7a183615e898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>57ecb322-2e2f-4427-add1-19fb8efb1f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passw' and @name = 'passw']</value>
      <webElementGuid>9bc287bc-a0b4-4ed7-abc4-d7a39968cf6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
