<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Congratulations_text</name>
   <tag></tag>
   <elementGuidId>41c9aac2-e9f3-493f-9151-2b9c7b0d8be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='_ctl0__ctl0_Content_Main_promo']/table/tbody/tr/td/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e2845d76-5ec5-46c9-adce-263bba54a3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Congratulations! </value>
      <webElementGuid>1f2d6fca-6dd3-452c-b509-9f4f6e0f6d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_ctl0__ctl0_Content_Main_promo&quot;)/table[1]/tbody[1]/tr[1]/td[1]/h2[1]</value>
      <webElementGuid>6c10ece6-e7fa-4593-b696-22d00b0f99fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_ctl0__ctl0_Content_Main_promo']/table/tbody/tr/td/h2</value>
      <webElementGuid>4d36e4a0-57d4-49a1-b37f-c1b92ab0c8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Account Details:'])[1]/following::h2[1]</value>
      <webElementGuid>9d2d8bf2-5ad4-4987-b70f-fb4e57541938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello John Smith'])[1]/following::h2[1]</value>
      <webElementGuid>64b138cb-0e84-4578-8bbf-e79b02f66b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have been pre-approved for an Altoro Gold Visa with a credit limit of $10000!'])[1]/preceding::h2[1]</value>
      <webElementGuid>9f92e414-c586-4699-bc92-e0b30fc90c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Congratulations!']/parent::*</value>
      <webElementGuid>c8aef73d-ec4c-4fa6-8b2b-b1bafe67b285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>82834869-a723-462e-a648-9505772cb2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Congratulations! ' or . = 'Congratulations! ')]</value>
      <webElementGuid>f4dd04b2-aa16-4543-8f7d-ecba99560b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
