<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getAccount_btn</name>
   <tag></tag>
   <elementGuidId>06a7c949-f5a6-4216-8e9c-7963011009e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnGetAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnGetAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27a09752-733d-4bad-a480-c887951c3502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>22c8387e-d382-421b-9fd2-aef21f1e79c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGetAccount</value>
      <webElementGuid>60fa03e0-7c61-40e5-a1b1-e4f811563a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>   GO   </value>
      <webElementGuid>bf1e20b9-5a1b-467b-919d-bab7083283f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGetAccount&quot;)</value>
      <webElementGuid>71ddfb76-124e-4d93-84ad-dceb45452b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnGetAccount']</value>
      <webElementGuid>9be1f62e-f363-4110-855f-9e539ffe730c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ee13df22-60fb-4dd9-8044-253636646832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnGetAccount']</value>
      <webElementGuid>6e22e861-2ec9-4936-a38a-ac4e5e9c410f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
