<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_Link</name>
   <tag></tag>
   <elementGuidId>4f06e233-600b-4e79-bde2-771b37215826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AccountLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AccountLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61cdcaa4-009b-4867-a1d8-28e51f21e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountLink</value>
      <webElementGuid>06fc517c-d38a-442b-8f44-f3cce25866d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login.jsp</value>
      <webElementGuid>ea41f9b2-d9c2-4052-8bba-ed44bb103f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus</value>
      <webElementGuid>37a87d08-8e31-47c3-8fa0-5be12b418c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ONLINE BANKING LOGIN</value>
      <webElementGuid>21b5a877-6968-4ad7-ae03-e01613cba5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountLink&quot;)</value>
      <webElementGuid>7a14c8d2-eae5-4f64-83c8-9d1b13c26ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AccountLink']</value>
      <webElementGuid>5688387c-40e7-49b7-afa7-9e42c2f77a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Header1']/a</value>
      <webElementGuid>7b8122eb-3e4c-4286-9a62-cf91f83e1730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ONLINE BANKING LOGIN')]</value>
      <webElementGuid>574bbdab-49da-4941-ab45-f77e01d7575e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>576ea071-41b9-4819-8dac-62d26b794ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::a[1]</value>
      <webElementGuid>343d5104-a621-4f1f-bb2d-d5afa6d90ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERSONAL'])[1]/preceding::a[1]</value>
      <webElementGuid>5545a029-393c-4106-ab13-abf9e8ef6a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMALL BUSINESS'])[1]/preceding::a[2]</value>
      <webElementGuid>05ffaa42-2cc4-4b5b-8fa8-dab069b515be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ONLINE BANKING LOGIN']/parent::*</value>
      <webElementGuid>0d04c971-4f49-431b-afd5-bca5210a63a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/login.jsp')])[2]</value>
      <webElementGuid>d1f89178-074b-4603-86de-8ca4fa76b8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>008182e8-8a6b-46a6-a021-d1d79404a13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AccountLink' and @href = '/login.jsp' and (text() = 'ONLINE BANKING LOGIN' or . = 'ONLINE BANKING LOGIN')]</value>
      <webElementGuid>11481856-f5d5-4531-a6e1-537d9955e28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
