<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonMoreTravel</name>
   <tag></tag>
   <elementGuidId>9498212d-8b4b-4b4b-b7b8-ad8d201e1951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.uitk-text.uitk-type-300.uitk-text-default-theme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@title='More travel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67ea81cd-2e35-4b3b-aed1-d7cbf3e07899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uitk-text uitk-type-300 uitk-text-default-theme</value>
      <webElementGuid>b40982c0-d52a-4ef8-bd18-beb56b8f5d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More travel</value>
      <webElementGuid>7234d3fc-b250-4893-bdce-b2f98564447e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-navigation&quot;)/div[@class=&quot;uitk-layout-flex-item uitk-layout-flex-item-flex-basis-zero uitk-layout-flex-item-flex-grow-0 uitk-menu uitk-menu-mounted&quot;]/button[@class=&quot;uitk-button uitk-button-large uitk-button-has-text uitk-button-tertiary uitk-menu-trigger global-navigation-nav-button&quot;]/div[@class=&quot;uitk-text uitk-type-300 uitk-text-default-theme&quot;]</value>
      <webElementGuid>871abde3-9efc-4701-8356-b4a3e2e9c7b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primary-navigation']/div/button/div</value>
      <webElementGuid>2dccfe3c-ceb5-48a3-a5e1-2e0f195ccc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>1f53a0d5-5025-4174-80d7-267e734f41b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'More travel' or . = 'More travel')]</value>
      <webElementGuid>ba090711-c697-4578-b5b1-845402cee876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
