<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ONLINE BANKING LOGIN</name>
   <tag></tag>
   <elementGuidId>e7c42f31-8fe3-48ce-b44c-10797e68d1cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AccountLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>daefb37a-d7c4-4472-bf64-c4d8cd8eba42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountLink</value>
      <webElementGuid>e4006168-ff99-4caf-a3d0-b63cfe28bfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login.jsp</value>
      <webElementGuid>5133b4e6-00e9-475a-9398-057d1c77130d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus</value>
      <webElementGuid>872659a0-8bdf-4876-8676-1f1d69e40404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ONLINE BANKING LOGIN</value>
      <webElementGuid>080e188f-5dfa-437e-9c5b-f46d349f168f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountLink&quot;)</value>
      <webElementGuid>431faae9-2ce8-4448-9de9-7629c5288799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AccountLink']</value>
      <webElementGuid>b3ccca58-df29-4708-a5d0-36cef7ce042e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Header1']/a</value>
      <webElementGuid>43118c1d-dc47-4dd0-9415-298fbff41c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ONLINE BANKING LOGIN')]</value>
      <webElementGuid>f0455531-c101-4808-a741-f4d658ed676b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>5d95e6a0-4540-4d3d-8a94-11546fbbe9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::a[1]</value>
      <webElementGuid>dc2720d1-a4d6-4d8c-a2c6-54e75042a986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERSONAL'])[1]/preceding::a[1]</value>
      <webElementGuid>a7d3d6b1-f011-44be-8494-f09a996ba346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMALL BUSINESS'])[1]/preceding::a[2]</value>
      <webElementGuid>6f12f27d-5225-43a9-a013-bfeeef54589f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ONLINE BANKING LOGIN']/parent::*</value>
      <webElementGuid>8b869cb6-0157-45b7-b037-2b4b57750711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/login.jsp')])[2]</value>
      <webElementGuid>bfca5fa0-7dcf-4720-85f2-2c7f32f69ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>57439c25-c1d8-4798-a28c-114a17064588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AccountLink' and @href = '/login.jsp' and (text() = 'ONLINE BANKING LOGIN' or . = 'ONLINE BANKING LOGIN')]</value>
      <webElementGuid>e2beb65a-c683-4488-b3c4-4d648f5f51cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
