<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Congratulations</name>
   <tag></tag>
   <elementGuidId>24141a53-5d96-4271-a540-0de5ab23163a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='_ctl0__ctl0_Content_Main_promo']/table/tbody/tr/td/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>0acdf40b-a8e8-4a81-abc8-b3ad51d462b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Congratulations! </value>
      <webElementGuid>f7b30e9d-d267-4d33-a90b-7dee4d9d0337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_ctl0__ctl0_Content_Main_promo&quot;)/table[1]/tbody[1]/tr[1]/td[1]/h2[1]</value>
      <webElementGuid>4bd88552-d1cb-42dd-abdf-3b18156aa775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_ctl0__ctl0_Content_Main_promo']/table/tbody/tr/td/h2</value>
      <webElementGuid>bbf2a91a-ff46-437f-9011-b6a4cc07e1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Account Details:'])[1]/following::h2[1]</value>
      <webElementGuid>a6ed9a92-0d7f-4dca-9e24-d7e9260e98c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello John Smith'])[1]/following::h2[1]</value>
      <webElementGuid>4caabd86-26a2-4caa-8710-cb4d13490644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have been pre-approved for an Altoro Gold Visa with a credit limit of $10000!'])[1]/preceding::h2[1]</value>
      <webElementGuid>e9d68269-71a4-4a9d-883e-d1abdfaa4579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Congratulations!']/parent::*</value>
      <webElementGuid>66059455-a58a-455d-a326-3051c246250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>a454dd89-fdc6-42a9-84b7-127c370b6a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Congratulations! ' or . = 'Congratulations! ')]</value>
      <webElementGuid>5cd7ead8-78fc-48c6-b4ea-b970f0f11e72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
