<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_uid</name>
   <tag></tag>
   <elementGuidId>9de05f63-c644-4c37-a28f-d1fc7163345d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90f6163f-949e-475b-a552-06973634e277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c1ba0a8-332d-426c-8c56-61a88a896bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uid</value>
      <webElementGuid>5fd4e33a-5cfd-4bb7-b1a5-b5468e2693e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uid</value>
      <webElementGuid>9ccfad7b-923f-41ef-9730-91396321c513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uid&quot;)</value>
      <webElementGuid>7d20260f-5eb4-4da4-b528-c08633f6766b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uid']</value>
      <webElementGuid>037ba1a9-bc56-4669-b52a-c54955aafa74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0d1d34fb-a1e3-45aa-90fa-5e5e3a5c9730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7f7f9afe-74dd-4bc8-b45d-6035756da78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uid' and @name = 'uid']</value>
      <webElementGuid>5981d686-5a1f-4ad5-b283-23fa7d0a1138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
