<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_View Account Details_btnGetAccount</name>
   <tag></tag>
   <elementGuidId>d58b7a9d-219e-4770-8196-c6da81726fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnGetAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnGetAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d84450-9cdd-41be-b386-03e0fe6c3f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d70b2cf8-2990-417e-85ac-41dbc96ce3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGetAccount</value>
      <webElementGuid>643aaf5c-a46e-4bc0-bae5-e108f6623850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>   GO   </value>
      <webElementGuid>51e14bf1-2b2c-4c78-977e-cc7cd9f8a777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGetAccount&quot;)</value>
      <webElementGuid>d12f3411-131f-4aac-9410-5447c3002206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnGetAccount']</value>
      <webElementGuid>f5c9651f-95b8-40ed-9ee2-597f158669d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/form/table/tbody/tr/td[2]/input</value>
      <webElementGuid>83f84221-c0cb-4327-a106-7f45af21bc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnGetAccount']</value>
      <webElementGuid>9dad534c-84c5-4d2d-8893-874fd5ab2d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
